# Generated by Django 4.2.2 on 2023-12-10 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondinfo',
            name='daily_task',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='invite_code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='link',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='per_order',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_a',
            field=models.ManyToManyField(related_name='my_team_a_gp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_a_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_team_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_b',
            field=models.ManyToManyField(related_name='my_team_b_gp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_b_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_team_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_c',
            field=models.ManyToManyField(related_name='my_team_c_gp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_c_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_team_c', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_recharge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='team_withdraw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='telegram',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='total_earn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='transaction_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='vip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secondinfo',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
