# Generated by Django 4.2.2 on 2023-12-10 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_secondinfo_daily_task_secondinfo_invite_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_method', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
