# Generated by Django 4.2.2 on 2023-12-10 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_withdrawmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondinfo',
            name='datetime_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_order', models.FloatField(default=0.2)),
                ('daily_task', models.IntegerField(default=0)),
                ('earn_today', models.FloatField(default=0)),
                ('date', models.DateField(null=True)),
                ('task_done', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NikeMallUserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_withdraw', models.BooleanField(default=False)),
                ('is_recharge', models.BooleanField(default=False)),
                ('value', models.IntegerField()),
                ('level_needed', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('datetime_set', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_datetime', models.CharField(max_length=200, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=25)),
                ('datetime_validation', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL)),
                ('withdraw_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app.withdrawmethod')),
            ],
        ),
    ]
