# Generated by Django 4.2.2 on 2023-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_secondinfo_datetime_joined_task_nikemalluserrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondinfo',
            name='p',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
