# Generated by Django 4.2.2 on 2023-12-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikemalluserrequest',
            name='value',
            field=models.FloatField(),
        ),
    ]
