# Generated by Django 4.2.2 on 2023-12-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmethod',
            name='adress',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='withdrawmethod',
            name='custom_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawmethod',
            name='network',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
