# Generated by Django 4.2.2 on 2023-12-18 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_withdrawmethod_adress_withdrawmethod_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmethod',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
