# Generated by Django 4.2.2 on 2023-12-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_withdrawmethod_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikemalluserrequest',
            name='transaction_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
