# Generated by Django 4.2.2 on 2023-12-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_vip_daily_earning_vip_monthly_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondinfo',
            name='user_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
