# Generated by Django 4.2.2 on 2023-12-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_device_userlogintemptation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogintemptation',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
