# Generated by Django 4.2.2 on 2023-12-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_devicerequest_userlogintemptation_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='ip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
