# Generated by Django 4.2.2 on 2023-12-30 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_admindata_balance_alter_admindata_lost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='apk/')),
                ('version', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
