# Generated by Django 4.2.2 on 2023-12-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='web_access',
            field=models.BooleanField(default=False),
        ),
    ]
