# Generated by Django 4.2.2 on 2024-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_admindata_web_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondinfo',
            name='mission_completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
