# Generated by Django 4.2.2 on 2024-01-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_secondinfo_mission_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='transaction',
            field=models.IntegerField(default=0),
        ),
    ]
