# Generated by Django 4.2.2 on 2024-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_vip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawmethod',
            name='custom_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
