# Generated by Django 4.2.2 on 2024-01-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_task_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='android_brand',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_adress',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nikemalluserrequest',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='secondinfo',
            name='link',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='secondinfo',
            name='telegram',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
